export {default as Header} from './1-header/Header'
export {default as Hero} from './2-hero/Hero'
export {default as Main} from './3-main/Main'
export {default as Contact} from './4-contact/Contact'
export {default as Footer} from './5-footer/Footer'